import os
import google.generativeai as genai
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from fastapi.middleware.cors import CORSMiddleware

# 1. Setup Google Gemini
# It will look for the key in your Render Environment Variables
genai.configure(api_key=os.environ.get("GOOGLE_API_KEY"))

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class AskRequest(BaseModel):
    user_query: str = Field(..., description="The question asked by the user")

class AskResponse(BaseModel):
    answer: str
    citation: str
    progress_boost: int

@app.post("/ask", response_model=AskResponse)
async def ask(request: AskRequest):
    # 2. Safety Check
    if not request.user_query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty")

    try:
        # 3. Call Google Gemini AI
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        # We give the AI a "persona" instruction
        prompt = (
            f"You are an expert UPSC Tutor for Indian Polity. "
            f"Answer this student question clearly and concisely: '{request.user_query}'. "
            f"If relevant, mention Articles or Constitution Parts."
        )
        
        response = model.generate_content(prompt)
        ai_text = response.text

        # 4. Return the Real Answer
        return {
            "answer": ai_text,
            "citation": "Generated by AI Tutor", 
            "progress_boost": 10
        }

    except Exception as e:
        # If the AI fails (e.g., bad key), tell us why
        print(f"AI Error: {e}")
        return {
            "answer": "I am having trouble accessing the archives (AI Error). Please check the API Key.",
            "citation": "System Error",
            "progress_boost": 0
        }
        
# -------- DIAGNOSTIC TOOL (Delete later) --------
@app.get("/check-models")
def check_models():
    try:
        import google.generativeai as genai
        available = []
        # Ask Google what models are available for this specific Key
        for m in genai.list_models():
            if 'generateContent' in m.supported_generation_methods:
                available.append(m.name)
        
        # Print to Render Logs so you can see it there
        print(f"--- AVAILABLE MODELS: {available} ---")
        
        return {"status": "success", "models": available}
    except Exception as e:
        print(f"--- ERROR CHECKING MODELS: {e} ---")
        return {"status": "error", "message": str(e)}
        
